GET http://localhost:3000/bids

###

GET http://localhost:3000/bids/Aloe

###

POST http://localhost:3000/bids/addBid
Content-Type: application/json
Accept: application/json

{
  "name": "Aloe",
  "bidPrice": 25,
  "createdBy": "Gabriela"
}

###

PATCH http://localhost:3000/bids/test
Content-Type: application/json
Accept: application/json

{
  "name": "Banana",
  "bidPrice": 40,
  "createdBy": "Gabriela"
}

###

DELETE http://localhost:3000/bids/Aloe

###